version: "2.2"
services:
  web:
    build:
      args:
        - NODE_ENV=development
      context: .
      dockerfile: Dockerfile
    container_name: openedx.devstack.learner_portal
    image: frontend-app-learner-portal_web:latest
    networks:
      - devstack_default
    volumes:
      - .:/edx/app:delegated
      - notused:/edx/app/node_modules
    ports:
      - "8734:8734"
    environment:
      - NODE_ENV=development
      - HOSTNAME=example.com
networks:
  devstack_default:
    external: true
volumes:
  notused:

